// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3jIbYsYT15xVl-TyWKl7hN23TL8FPttQ',
    appId: '1:611343030352:web:b39d9cea700f2a345ed955',
    messagingSenderId: '611343030352',
    projectId: 'pets-org',
    authDomain: 'pets-org.firebaseapp.com',
    storageBucket: 'pets-org.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD48fUCte5k7fVyyeX5N5iPE7x_Es6gviU',
    appId: '1:611343030352:android:6aabaa816f67cbfe5ed955',
    messagingSenderId: '611343030352',
    projectId: 'pets-org',
    storageBucket: 'pets-org.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMzRFkgBtlGBJyQgQrjopXbqZz8fG63UI',
    appId: '1:611343030352:ios:2eedb8ef290cf14b5ed955',
    messagingSenderId: '611343030352',
    projectId: 'pets-org',
    storageBucket: 'pets-org.appspot.com',
    iosClientId: '611343030352-eqfbgq0rude5vujgms2h92rcchi9kupb.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMzRFkgBtlGBJyQgQrjopXbqZz8fG63UI',
    appId: '1:611343030352:ios:2eedb8ef290cf14b5ed955',
    messagingSenderId: '611343030352',
    projectId: 'pets-org',
    storageBucket: 'pets-org.appspot.com',
    iosClientId: '611343030352-eqfbgq0rude5vujgms2h92rcchi9kupb.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLogin',
  );
}
